version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  app:
    image: conecta4-springboot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9023:9023"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/conecta4
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=admin
    depends_on:
      - db

  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: conecta4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data:
